import { getRandomInt } from './getRandom';
// Hue Picker based on color selected on dropdown
export const hue = (color:string)=>{
    if(color === 'All Colors')return getRandomInt(360,0)
    if(color === 'Red')return getRandomInt(15,0)
    if(color === "Vermilion")return getRandomInt(30,15)
    if(color === "Orange")return getRandomInt(45,30)
    if(color === "Golden Yellow")return getRandomInt(60,45)
    if(color === "Lemon Yellow")return getRandomInt(75,60)
    if(color === "Yellowish Green")return getRandomInt(90,75)
    if(color === "Chartreuse")return getRandomInt(105,90)
    if(color === "Leaf Green")return getRandomInt(120,105)
    if(color === "Green")return getRandomInt(135,120)
    if(color === "Cobalt Green")return getRandomInt(150,135)
    if(color === "Emerald Green")return getRandomInt(165,150)
    if(color === "Turquoise Green")return getRandomInt(180,165)
    if(color === "Cyan")return getRandomInt(195,180)
    if(color === "Cerulean Blue")return getRandomInt(210,195)
    if(color === "Azure")return getRandomInt(225,210)
    if(color === "Cobalt Blue")return getRandomInt(240,225)
    if(color === "Blue")return getRandomInt(255,240)
    if(color === "Hyacinth")return getRandomInt(270,255)
    if(color === "Violet")return getRandomInt(285,270)
    if(color === "Purple")return getRandomInt(300,285)
    if(color === "Magenta")return getRandomInt(315,300)
    if(color === "Reddish Purple")return getRandomInt(330,315)
    if(color === "Ruby Red")return getRandomInt(345,330)
    if(color === "Carmine")return getRandomInt(360,345)
  }